version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: engnet-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: teste_db
    ports:
      - "5432:5432"

